docs: formula, migrate luckysheet
dream-num/univer.ai pull request #242
Opened 2024-08-20 13:26 UTC by Dushusir

2024-08-20 13:46 UTC, hexf00 approved these changes

2024-08-21 02:37 UTC, jikkai requested changes

2024-08-21 02:37 UTC, jikkai commented on src/docs/guides/general/advanced/custom-formula.en-US.mdx
> +        functionEnUS,
Excessive commas

2024-08-21 02:37 UTC, jikkai commented on src/docs/guides/general/advanced/custom-formula.zh-CN.mdx
> +        functionEnUS,
Excessive commas

2024-08-22 11:48 UTC, jikkai approved these changes

2024-08-22 11:48 UTC, merged